- name: Disable Gnome Wayland session
  ansible.builtin.replace:
    path: "/etc/gdm3/custom.conf"
    regexp: '#WaylandEnable=false'
    replace: "WaylandEnable=false"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    
- name: Update apt repo and cache on all Debian/Ubuntu boxes
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Upgrade all packages on servers
  apt: upgrade=dist force_apt_get=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    upgrade: dist

- name: Install build-essential
  apt: 
      name:
        - build-essential
      state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Remove Nvidia driver package
  ansible.builtin.apt:
    name: nvidia-*
    state: absent
  ignore_errors: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Nvidia driver version 535
  apt: 
      name:
        - nvidia-driver-535
      state: latest 
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Switch to nvidia GPU 
  shell: prime-select nvidia
  become: true

- name: Search user of machine
  shell: ls /home
  register: user_name

- name: Switch to nvidia GPU in the first start 
  ansible.builtin.cron:
    name: "Change to nvidia performance mode"
    job: "touch /home/{{user_name.stdout}}/Desktop/PleaseNOTRestartComputer && prime-select nvidia && rm -f /home/{{user_name.stdout}}/Desktop/PleaseNOTRestartComputer"
