- name: Remove route remote host in ovpn file
  ansible.builtin.replace:
    path: /home/*/Documents/VPN/*.ovpn
    regexp: "^#route remote_host 255.255.255.255 net_gateway"
    replace: " "

- name: Load openvpn ovpn from ~/Documents/VPN
  shell: nmcli connection import type openvpn file /home/*/Documents/VPN/*.ovpn
  become: true